name: Build
on:
  - push
jobs:
  Build-Linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies (apt)
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get -y install zlib1g-dev libjpeg-dev devscripts python3-all-dev debhelper python3-pil python3-numpy dh-python

      - name: Install dependencies (pip)
        run: python -m pip install numpy Pillow==9.1.1

      - name: Clone Pillow 9.1.1
        run: git clone --branch=9.1.1 --depth=1 https://github.com/python-pillow/Pillow.git /tmp/pillow_checkout

      - name: Build extension
        run: env PIL_INCLUDE_DIR=/tmp/pillow_checkout/src/libImaging/ python setup.py build

      - name: Create .deb changelog
        run: |
          export VERSION=$(python3 setup.py --version)
          export DESC=$(git describe --tags)
          export DATE=$(date -u +'%a, %d %b %Y %H:%M:%S %z')
          envsubst < debian/changelog.in > debian/changelog

      - name: Build .deb
        run: env DEB_BUILD_OPTIONS=nocheck debuild -i -us -uc -b -Zxz

      - name: List deb files
        run: ls -l ../*.deb

  Build-Windows-x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3

      - name: Install dependencies (pip)
        run: python -m pip install numpy pillow

      - name: Build extension
        run: python setup.py build
